CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS auth(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    authToken VARCHAR(64) NOT NULL UNIQUE,
);

CREATE TABLE IF NOT EXISTS chessGames(
    gameID INT AUTO_INCREMENT PRIMARY KEY,
    whiteUsername VARCHAR(50) NOT NULL UNIQUE,
    blackUsername VARCHAR(50) NOT NULL UNIQUE,
    gameName VARCHAR(50) NOT NULL,
    game JSON NOT NULL
);