package server;

import com.google.gson.Gson;
import spark.*;

public class Server {

    public int run(int desiredPort) {
        Spark.port(desiredPort);

        Spark.staticFiles.location("web");

        // Register your endpoints and handle exceptions here.

        // This line initializes the server and can be removed once you have a
        // functioning endpoint
        Spark.init();

        Spark.post("/user", this::registerUser);
        Spark.get("/session", this::login);
        Spark.delete("/session", this::logout);
        Spark.get("/game", this::listGames);
        Spark.post("/game", this::createGame);
        Spark.put("/game", this::joinGame);
        Spark.delete("/db", this::clearApplication);

        Spark.awaitInitialization();


        // Register
        Spark.post("/user", (req, res) -> {
            // Handle user creation logic here
            try {
                String username = req.queryParams("username");
                String password = req.queryParams("password");
                String email = req.queryParams("email");
                if (username.equals("ben") && password.equals("pass")) {
                    res.status(200);
                    return "{\"username\":\"\", \"authToken\":\"\"}";
                }
                if (username.equals("ben") && !password.equals("pass")) {
                    res.status(400);
                    return "{\"message\": \"Error: bad request.\"}";
                }
                // Check if username is in database

                // Simulate user creation
                // In a real application, you would interact with your data access layer here
                return "{\"message\": \"User created!\"}";
            } catch (Exception e) {
                res.status(500);
                return "{\"error\": \"Failed to create user.\"}";
            }
        });
        // Mostly autogenerated code. Come back to this later
        // Login
        Spark.get("/session", (req, res) -> {
            // Handle session creation logic here
            try {
                String username = req.queryParams("username");
                String password = req.queryParams("password");
                // Check if username and password are correct

                // Simulate session creation
                // In a real application, you would interact with your data access layer here
                return "{\"message\": \"Session created!\"}";
            } catch (Exception e) {
                res.status(500);
                return "{\"error\": \"Failed to create session.\"}";
            }
        });

        // Logout
        Spark.delete("/session", (req, res) -> {
            try{
                res.status(200);
                return "{\"message\": \"Cleared all data!\"}";
            } catch(Exception e) {
                res.status(500);
                return "{\"erro\": \"Description of error\"}";
            }
        });

        // List games
        Spark.get("/game", (req, res) -> {
            try{
                res.status(200);
                return "{\"message\": \"Cleared all data!\"}";
            } catch(Exception e) {
                res.status(500);
                return "{\"erro\": \"Description of error\"}";
            }
        });
        // Create a new game
        Spark.post("/game", (req, res) -> {
            try{
                res.status(200);
                return "{\"message\": \"Cleared all data!\"}";
            } catch(Exception e) {
                res.status(500);
                return "{\"erro\": \"Description of error\"}";
            }
        });
        // Join game
        Spark.put("/game", (req, res) -> {
            try{
                res.status(200);
                return "{\"message\": \"Cleared all data!\"}";
            } catch(Exception e) {
                res.status(500);
                return "{\"erro\": \"Description of error\"}";
            }
        });

        Spark.delete("/db", (req, res) -> {
            try{
                res.status(200);
                return "{\"message\": \"Cleared all data!\"}";
            } catch(Exception e) {
                res.status(500);
                return "{\"erro\": \"Description of error\"}";
            }
            
        });
        return Spark.port();

    }
    private Object registerUser (Request req, Response res) {
        return "";
    }
    private Object login (Request req, Response res) {
        return "";
    }
    private Object logout (Request req, Response res) {
        return "";
    }
    private Object listGames (Request req, Response res) {
        return "";
    }
    private Object createGame (Request req, Response res) {
        return "";
    }
    private Object joinGame (Request req, Response res) {
        return "";
    }
    private Object clearApplication (Request req, Response res) {
        return "";
    }


    public void stop() {
        Spark.stop();
        Spark.awaitStop();
    }
}
