package server;

import spark.*;

public class Server {

    public int run(int desiredPort) {
        Spark.port(desiredPort);

        Spark.staticFiles.location("web");

        // Register your endpoints and handle exceptions here.

        // This line initializes the server and can be removed once you have a
        // functioning endpoint
        Spark.init();

        Spark.awaitInitialization();
        
        //Switch to post later
        //Register
        Spark.get("/user", (req, res) -> {
            // Handle user creation logic here
            try {
                String username = req.queryParams("username");
                String password = req.queryParams("password");
                String email = req.queryParams("email");
                if (username.equals("ben")) {
                    res.status(200);
                    return "{\"error\": \"Reutrn first.\"}";
                }
                if (username != "ben") {
                    res.status(400);
                    return "{\"error\": \"Return second.\"}";
                }
                // Check if username is in database

                // Simulate user creation
                // In a real application, you would interact with your data access layer here
                return "{\"message\": \"User created!\"}";
            } catch (Exception e) {
                res.status(500);
                return "{\"error\": \"Failed to create user.\"}";
            }
        });
        //Mostly autogenerated code. Come back to this later
        //Login
        Spark.post("/session", (req, res) -> {
            // Handle session creation logic here
            try {
                String username = req.queryParams("username");
                String password = req.queryParams("password");
                // Check if username and password are correct

                // Simulate session creation
                // In a real application, you would interact with your data access layer here
                return "{\"message\": \"Session created!\"}";
            } catch (Exception e) {
                res.status(500);
                return "{\"error\": \"Failed to create session.\"}";
            }
        });

        //Logout
        Spark.delete("/session", (req, res) -> {
            return"{\"message\": \"Session deleted!\"}";
        });

        //List games
        Spark.get("/game", (req, res) -> {
            return"{\"message\": \"List all games!\"}";
        });

        //Create a new game
        Spark.post("/game", (req, res) -> {
            return"{\"message\": \"Created new game!\"}";
        });

        //Join game
        Spark.put("/game", (req, res) -> {
            return"{\"message\": \"Joined game!\"}";
        });

        Spark.get("/test", (req, res) -> {
            return "{\"message\": \"Hello from Spark Java!\"}";
        });
        return Spark.port();

    }

    // public void clear(){
    // Spark.delete(/db){
    // // Clear the database here
    // // return 0;
    // }
    // }

    public void stop() {
        Spark.stop();
        Spark.awaitStop();
    }
}
